// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQmDE2QLfcruRo5Lb5dDgGmnF9SLsC-no',
    appId: '1:1028973143034:web:25e4f44c340a9ddb133a43',
    messagingSenderId: '1028973143034',
    projectId: 'chatapp-ae215',
    authDomain: 'chatapp-ae215.firebaseapp.com',
    storageBucket: 'chatapp-ae215.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLfN1xG5HUYEmOkHZPL45n78QWGGujSKU',
    appId: '1:1028973143034:android:29ee315b9955d261133a43',
    messagingSenderId: '1028973143034',
    projectId: 'chatapp-ae215',
    storageBucket: 'chatapp-ae215.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdqn5DQO-pWL_9YPjMcPd5bmrF19kGeDY',
    appId: '1:1028973143034:ios:ceb334a3f7d7b242133a43',
    messagingSenderId: '1028973143034',
    projectId: 'chatapp-ae215',
    storageBucket: 'chatapp-ae215.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdqn5DQO-pWL_9YPjMcPd5bmrF19kGeDY',
    appId: '1:1028973143034:ios:ceb334a3f7d7b242133a43',
    messagingSenderId: '1028973143034',
    projectId: 'chatapp-ae215',
    storageBucket: 'chatapp-ae215.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQmDE2QLfcruRo5Lb5dDgGmnF9SLsC-no',
    appId: '1:1028973143034:web:2fa6df942bc6ca1c133a43',
    messagingSenderId: '1028973143034',
    projectId: 'chatapp-ae215',
    authDomain: 'chatapp-ae215.firebaseapp.com',
    storageBucket: 'chatapp-ae215.firebasestorage.app',
  );
}
